FROM golang:1.19-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /catchup-x-post-web ./cmd/web

FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /catchup-x-post-web /app/catchup-x-post-web

ENTRYPOINT ["/app/catchup-x-post-web"]
